version: '3.3'
services:
  mysql-db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'mysql-db'
      MYSQL_USER: 'mysql-user'
      MYSQL_PASSWORD: 'mysql-password'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    # volumes:
    #   - my_project_mysql_data:/var/lib/mysql
  rabbit-mq:
    image: rabbitmq:3.9-management-alpine
    ports:
      - '5672:5672'
  php-apache:
    container_name: php-apache
    build:
      context: ./server
    ports:
      - '8080:80'
    volumes:
      - ./server:/var/www/html
      # - ./.docker/apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
    depends_on:
      - mysql-db
      - rabbit-mq
    restart: on-failure
